### ISSUE TITLE
[Admin Portal] Object names should display properly within database 

### ISSUE THREAD

**Issue by akiqua** [CSC394-FoodTeam/food-waste-app#26]
![Image](https://user-images.githubusercontent.com/40920446/217599149-d3e194bf-ef50-4876-a920-5524c400b0a3.png)

**Comment by dan-k3** [comment]
![Image](https://user-images.githubusercontent.com/40920446/218015954-89507e18-d774-4ac3-96ea-9ce67f620f25.png)
